/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class HighlightOptions {
  classes: Array<string>
}
export type HighlightManager = Highlighter
export class Highlighter {
  constructor(options: any)
  supportedLanguages(): Array<string>
  isSupported(language: string): boolean
  highlight(code: string, language: string): any
}
