/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface HastProperties {
  className: string
}
export interface HastNode {
  type: string
  tagName: string
  properties: HastProperties
  children: Array<HastNode | HastTextNode>
}
export interface HastTextNode {
  type: string
  value: string
}
export type JsHighlighter = Highlighter
export class Highlighter {
  readonly highlightNames: Array<string>
  constructor(highlightNames?: Array<string> | undefined | null)
  supportedLanguages(): Array<string>
  isSupported(language: string): boolean
  highlight(code: string, language: string): HastNode
}
