#!/usr/bin/sh

ls highlight-* >/dev/null 2>&1
no_prefix=$?

ls highlight.*.node >/dev/null 2>&1
with_prefix=$?

# Exit with 0 if either condition is true, otherwise exit with 1
if [ "$no_prefix" -eq 0 ] || [ "$with_prefix" -eq 0 ]; then
    exit 0
else
    exit 1
fi
