[package]
name = "highlight"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tree-sitter-highlight = "0.24"

tree-sitter-javascript = "0.23"
tree-sitter-typescript = "0.23"
tree-sitter-rust = "0.23"
tree-sitter-css = "0.23"
tree-sitter-regex = "0.24"
tree-sitter-html = "0.23"
tree-sitter-glsl = { path = "./parsers/tree-sitter-glsl" }

napi-sys = "2.4"
napi = "2.16"
napi-derive = "2.16"

ordered-float = "4.6"
ahash = "0.8"

paste = { git = "https://github.com/Caellian/paste.git" }
thiserror = "2.0"

[build-dependencies]
serde = {version = "1.0", features = ["derive"]}
ron = "0.8"

napi-build = { version = "2" }

[profile.release]
opt-level = 3
lto = true
