name: Build sources and publish

on:
  push:
    branches: [trunk]
    paths:
      - src/**
      - blog-builder/posts/**/*.md
      - blog-builder/*.js
      - blog-builder/*.json
      - highlight/index.js
      - highlight/*.json
      - highlight/build.rs
      - highlight/Cargo.toml
      - highlight/src/**
      - .github/workflows/update.yml
      - package.json

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Cache blog node modules
        uses: actions/cache@v2
        with:
          path: "blog-builder/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('blog-builder/package-lock.json') }}
      - name: Cache highlight node modules
        uses: actions/cache@v2
        with:
          path: "highlight/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('highlight/package-lock.json') }}
      - name: Cache icon data
        uses: actions/cache@v2
        with:
          path: "src/data/icons.json"
          key: ${{ runner.os }}-modules-${{ hashFiles('art/icons/**') }}
      - name: Cache highlight binary
        uses: actions/cache@v2
        with:
          path: |
            highlight/highlight*
            highlight/index.js
          key: ${{ runner.os }}-highlight-${{ hashFiles('highlight/src/**') }}-${{ hashFiles('highlight/extensions/**') }}
      - name: Cache post content
        uses: actions/cache@v2
        with:
          path: "blog-builder/out"
          key: posts
      - name: Install and build dependencies
        run: |
          npm clean-install
          npm run build:pre
      - name: Build
        run: npm run build
      - name: Upload generated files artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-cloudflare
          path: .svelte-kit/cloudflare
          retention-days: 2
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 488cd81c3f29e24045082a0173c4976f
          projectName: portfolio
          directory: .svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}