name: Build sources and publish

on:
  push:
    branches: [trunk]
    paths:
      - src/**
      - blog-builder/*.js
      - blog-builder/*.json
      - highlight/index.js
      - highlight/*.json
      - highlight/build.rs
      - highlight/Cargo.toml
      - highlight/src/**
      - .github/workflows/update.yml
      - package.json

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Cache blog node modules
        uses: actions/cache@v2
        with:
          path: "blog-builder/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('blog-builder/package-lock.json') }}
      - name: Cache highlight node modules
        uses: actions/cache@v2
        with:
          path: "highlight/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('highlight/package-lock.json') }}
      - name: Cache icon data
        uses: actions/cache@v2
        with:
          path: "src/data/icons.json"
          key: ${{ runner.os }}-modules-${{ hashFiles('art/icons/**') }}
      - name: Install dependencies
        run: |
          npm clean-install
          npm run build:pre
      - name: Build sources head
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: portfolio-cloudflare
          path: .svelte-kit/cloudflare
          retention-days: 7
