name: update-served

on:
  push:
    branches: [sources]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources branch
        uses: actions/checkout@v2
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: "master"
          path: "build"
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm install
      - name: Move .git during build
        run: |
          ls -lah build
          mv build/.git build-git
          ls -lah
      - name: Build sources head
        run: npm run build
      - name: Move 404
        run: |
          mv build/404/index.html build/404.html
          rmdir build/404
      - name: Return .git after build
        run: |
          ls -lah
          mv build-git build/.git
          ls -lah build
      - name: Commit updated master branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: build
          commit_message: Updated served page
          branch: ${{ github.head_ref }}
          commit_options: "--no-verify --signoff"
          commit_user_name: Automated build
