name: update-served

on:
  push:
    branches: [sources]
    paths:
      - src/**

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources branch
        uses: actions/checkout@v2
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: "master"
          path: ".svelte-kit/cloudflare"
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install libkrb5-dev
        run: sudo apt-get install libkrb5-dev gcc
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}s
      - name: Install dependencies
        run: |
          npm install
      - name: Move .git during build
        run: |
          ls -lah .svelte-kit/cloudflare
          mv .svelte-kit/cloudflare/.git build-git
          ls -lah
      - name: Build sources head
        run: npm run build
      - name: Return .git after build
        run: |
          ls -lah
          mv build-git .svelte-kit/cloudflare/.git
          ls -lah .svelte-kit/cloudflare
      - name: Commit updated master branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .svelte-kit/cloudflare
          commit_message: Updated served page
          branch: ${{ github.head_ref }}
          commit_options: "--no-verify --signoff"
          commit_user_name: Automated build
