name: Build sources and publish

on:
  push:
    paths:
      - src/**
      - blog-builder/posts
      - blog-builder/*.js
      - blog-builder/*.json
      - highlight/index.js
      - highlight/*.json
      - highlight/build.rs
      - highlight/Cargo.toml
      - highlight/src/**
      - .github/workflows/update.yml
      - package.json

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Fetch Post Git History
        run: |
          cd blog-builder/posts
          git fetch --unshallow
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Cache blog node modules
        uses: actions/cache@v4
        with:
          path: "blog-builder/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('blog-builder/package-lock.json') }}
      - name: Cache highlight node modules
        uses: actions/cache@v4
        with:
          path: "highlight/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('blog-builder/highlight/package-lock.json') }}
      - name: Cache highlight binary
        uses: actions/cache@v4
        with:
          path: |
            blog-builder/highlight/highlight*
            blog-builder/highlight/index.js
          key: ${{ runner.os }}-highlight-${{ hashFiles('blog-builder/highlight/src/**', 'blog-builder/highlight/extensions/**') }}
      - name: Cache post content
        uses: actions/cache@v4
        with:
          path: blog-builder/out
          key: |
            posts-${{ hashFiles('blog-builder/highlight/src/**', 'blog-builder/highlight/extensions/**', 'blog-builder/*.js', 'blog-builder/package*.json') }}
      - name: Install dependencies
        run: npm clean-install
      - name: Test blog builder
        run: npm run test --prefix ./blog-builder
      - name: Generate blog content
        run: npm run build:pre
      - name: Build
        run: npm run build
      - name: Note generated files size
        run: |
          size=$(du -hs .svelte-kit/cloudflare | cut -d$'\t' -f 1)
          echo "Size: ${size}iB"
          echo -e "**Total deployment size:** ${size}iB\n" >> $GITHUB_STEP_SUMMARY
      - name: Upload generated post data artifact
        uses: actions/upload-artifact@v4
        with:
          name: post-data
          path: blog-builder/out
          retention-days: 2
      - name: Upload generated files artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-cloudflare
          path: .svelte-kit/cloudflare
          retention-days: 2
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .svelte-kit/cloudflare --project-name=portfolio --commit-dirty=true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}